SUNNY_2_RAINY_PROMPT = [
    "Transform the bright daylight into a nocturnal downpour",
    "Convert the sunlit day into a night filled with rain",
    "Change a day of sunshine into a rainy evening",
    "Shift from a sun-filled day to a night showered in rain",
    "Alter a sunny afternoon into a stormy night",
    "Make a day under the sun become a night under the clouds",
    "Turn the daylight's brightness into nighttime rainfalls",
    "Morph a sun-drenched day into a rain-drenched night",
    "Flip a sunny morning into a wet night",
    "Switch the sunny hours into rainy nighttime",
    "Transition from a clear day to a rainy dark",
    "Modify a sunny landscape into a rainy nightscape",
    "Evolve the sunny skies into rainy night skies",
    "Transform the daytime warmth into a cool, rainy night",
    "Convert the day's sunshine into evening showers",
    "Change a sunny scene into a night filled with rainfall",
    "Shift the sunny weather into a night of rain",
    "Alter a bright sunny day into a dark rainy night",
    "Make the clear blue sky turn into a rainy night sky",
    "Turn the day's sunlight into night's rain clouds",
    "Morph a sunbeam-filled day into a rainy gloom night",
    "Flip a day of clear skies into a night of rain",
    "Switch from sunny warmth to rainy coolness at night",
    "Transition the sunny calm into a stormy night",
    "Modify the daylight clarity into nighttime precipitation",
    "Evolve the day's brightness into a night's raininess",
    "Transform a sunny existence into a nocturnal rain",
    "Convert the day's radiance into a night soaked in rain",
    "Change the sunny outdoors into a wet, rainy night",
    "Shift the sunny ambiance into a rainy night's embrace",
    "Alter the sun's reign into a night showered by rain",
    "Make the sunny clarity turn into a murky rainy night",
    "Turn the day's sun into the night's rain showers",
    "Morph the bright day into a dark, rainy night",
    "Flip a sunny reality into a nighttime rain",
    "Switch a day of sunlight into a night of raindrops",
    "Transition a sunny forecast into a rainy night forecast",
    "Modify a sunny disposition into a rainy night mood",
    "Evolve the day's light into night's rain",
    "Transform sunny moments into rainy night moments",
    "Convert a sunny setting into a setting drenched by night rain",
    "Change a day bathed in sunlight into a night washed with rain",
    "Shift from a sunny spectacle to a nocturnal rain spectacle",
    "Alter the sun's warmth into the coolness of rain at night",
    "Make a sunny space into a space filled with night rain",
    "Turn a sunny period into a period of night rain",
    "Morph a day of sunshine into a night of raining",
    "Flip the daytime sun into nighttime rainfall",
    "Switch a sunny existence for a rain-filled night existence",
    "Transition from the light of day to the rains of night",
]
